### ISSUE TITLE
.get() in python3.8.2 

### ISSUE THREAD

**Issue by pateshix** [snoopyjc/pythonizer#2]
Issue .get() in python3.8.2

setenv PATH /usr/xdllc/pkgs/python3/3.8.2/bin:${PATH}  
 # You were absolutely Correct - they lied to me before it was a hard link to 3.4

"" ERROR STATISTICS:  W: 1 ""   Is this bad ?? 

plxcji019>    r_e_q.py    Q_t_25_r.in
  File "r_e_q.py", line 915
    tc.append(.get(tc_def))
                    ^
SyntaxError: invalid syntax

tc.append(.get(tc_def)) instances: 
        Line 5:     tc.append(.get(tc_def))
	Line 442:  300 | 2 |   |        tc.append(.get(tc_def))                                                         #PL: 
	Line 453:  300 | 2 |   |        tc.append(.get(tc_def))

.get() instances
        Line 5:     tc.append(.get(tc_def))
	Line 194:   55 | 3 |   |            devtype = tc[idev].get('type')                                              #PL: $cellname=$tc[$idev]{cellname};
	Line 195:   56 | 3 |   |            cellname = tc[idev].get('cellname')                                         #PL: $wid=$tc[$idev]{wid};
	Line 196:   57 | 3 |   |            wid = tc[idev].get('wid')                                                   #PL: $len=$tc[$idev]{len};
	Line 197:   58 | 3 |   |            len_ = tc[idev].get('len')                                                  #PL: $spacing=$tc[$idev]{spacing};
	Line 198:   59 | 3 |   |            spacing = tc[idev].get('spacing')                                           #PL: if ( exists($tc[$idev]{options})) {
	Line 200:   61 | 4 |   |                emx_extra_option = tc[idev].get('options')                              #PL: } else {
	Line 204:   66 | 4 |   |                port1 = tc[idev].get('port')                                            #PL: } else {
	Line 208:   71 | 4 |   |                simfreq = tc[idev].get('simfreq')                                       #PL: } else {
	Line 442:  300 | 2 |   |        tc.append(.get(tc_def))                                                         #PL: 

is the rest of logfile in /tmp/Pythonizer ?? required?

**Comment by pateshix** [comment]
#!/usr/bin/env python3   .get example that works even in 3.6
#/usr/bin/python3 -u
#!/usr/intel/pkgs/python3/3.8.2

import requests

x = requests.get('https://w3schools.com/python/demopage.htm')

print(x.text)

**Comment by pateshix** [comment]
.get attribute failure -

plxcji019> getm.py
Traceback (most recent call last):
  File "getm.py", line 9, in <module>
    y = math.get('pi')
AttributeError: module 'math' has no attribute 'get'
plxcji019> less !$
less getm.py
plxcji019> more !$
more getm.py
#!/usr/bin/env python3
#/usr/bin/python3 -u
#!/usr/intel/pkgs/python3/3.8.2

#import numpy
import math
 
#x = numpy.get('pi')
y = math.get('pi')

#print(x.text)
print(y.text)

**Comment by snoopyjc** [comment]
Can you attach the perl source code or at least a snippet of it that reproduces the problem?

**Comment by snoopyjc** [comment]
Please also try it with v0.965

**Comment by pateshix** [comment]
Now I get a File Module error – is it an import error or something else – just hangs – never completes now

[2:37 PM] Ateshian, PeterX Roy
Latest version of Conv2.... /nfs/pdx/disks/x5e2d_circuit_simulation_gwa001/pateshix/conv_pl_py_1 - still has file module problem - If you have some Python help on this please let me know -

[2:41 PM] Ateshian, PeterX Roy
Post mortem debugger finished. The Conv2portParams_hz_new.py will be restarted
> /nfs/pdx/disks/x5e2d_circuit_simulation_gwa001/pateshix/conv_pl_py_1/Conv2portParams_hz_new.py(8)<module>()
-> import builtins,re,io,subprocess,tempfile,warnings,sys,collections.abc,inspect,types,os, math, cmath
(Pdb)
Traceback (most recent call last):
File "/usr/intel/pkgs/python3/3.8.2/lib/python3.8/pdb.py", line 1703, in main
pdb._runscript(mainpyfile)
File "/usr/intel/pkgs/python3/3.8.2/lib/python3.8/pdb.py", line 1572, in _runscript
self.run(statement)
File "/usr/intel/pkgs/python3/3.8.2/lib/python3.8/bdb.py", line 580, in run
exec(cmd, globals, locals)
File "<string>", line 1, in <module>
File "/nfs/pdx/disks/x5e2d_circuit_simulation_gwa001/pateshix/conv_pl_py_1/Conv2portParams_hz_new.py", line 8, in <module>
import builtins,re,io,subprocess,tempfile,warnings,sys,collections.abc,inspect,types,os, math, cmath
ModuleNotFoundError: No module named 'File'
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /nfs/pdx/disks/x5e2d_circuit_simulation_gwa001/pateshix/conv_pl_py_1/Conv2portParams_hz_new.py(8)<module>()
-> import builtins,re,io,subprocess,tempfile,warnings,sys,collections.abc,inspect,types,os, math, cmath

[2:41 PM] Ateshian, PeterX Roy
plxcji019> grep File Conv2*
return tempfile.TemporaryFile(mode=mode, encoding=encoding)
#_carp(f"close failed: Filehandle is already closed", skip=2)
import File.Spec as _File_Spec
plxcji019>

**Comment by snoopyjc** [comment]
It’s difficult to see what’s going on without seeing the original Perl source but try commenting out the “import File.Spec…” line in the generated code and see how much farther you get.  What File::Spec function do you need?  I have implemented some of them but not all.

**Comment by pateshix** [comment]
Thank you very much for Version 0.965….. working with it now –

**Comment by pateshix** [comment]
## From original perl5
##
#!/usr/intel/bin/perl -w
use Math::Complex;
use File::Spec;
use Cwd;
## file operations below VVVVVVV
$Z0 = 50.0;
$freq_mult = 1;
$ri = 1;
$pi = 3.1415927;
@freq = ();
@s11 = (); @s21 = (); @s12 = (); @s22 = ();
@z11 = (); @z21 = (); @z12 = (); @z22 = ();
@y11 = (); @y21 = (); @y12 = (); @y22 = ();
if($#ARGV != 0){ die("Usage: Conv2portParams.pl <2port Sparams>\n"); }

&readSparams();
# &printSparams();
@fileLst = split('\.',$ARGV[0]);
$yfile = $fileLst[0]."\.y2p";
$lqfile = $fileLst[0]."\.lq";
&ConvStoZ();
&ConvStoY();
&PrintYandLQ();
1;

sub PrintYandLQ()
{
my $i=0;
my $l = 0;
my $q = 0;
my $z = 0;
my $res = 0;
my $omega = 0;
my $freqghz = 0;
open(YFILE,">$yfile") || die("Can not write to $yfile: $!\n");
open(LQFILE,">$lqfile") || die("Can not write to $lqfile: $!\n");
print(YFILE "# Hz Y RI\n");
print(LQFILE "Freq_HZ \tL \tQ \tLfrY \tQfrY \tR\n");

**Comment by snoopyjc** [comment]
The perl File::Spec methods are documented here: https://perldoc.perl.org/File::Spec - which ones does you code call?  If none, you can safely comment out the "use File::Spec;" line and try again.
